theme = "everforest_dark"

[editor]
line-number = "relative"
shell = ["fish", "-c"]
idle-timeout = 100
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
"#" = "toggle_comments"

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
space = ":fmt"
ret = ":w!"

[keys.normal.space.x]
i = ":pipe ex_s ip"

[keys.normal.space.x.I]
i = ":pipe ex_s i"
p = ":pipe ex_s ip"
f = ":pipe ex_s if"
r = ":pipe ex_s ifr"

[keys.normal.space.x.c]
s = ":pipe ccase -t snake | tr -d '\n'"
c = ":pipe ccase -t camel | tr -d '\n'"
k = ":pipe ccase -t kebab | tr -d '\n'"
t = ":pipe ccase -t title | tr -d '\n'"
