theme = "everforest_dark"

[editor]
line-number = "relative"
shell = ["fish", "-c"]
idle-timeout = 100
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
space = ":fmt"
ret = ":w!"
