theme = "everforest_dark"

[editor]
line-number = "relative"
shell = ["fish", "-c"]
idle-timeout = 100
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
"#" = "toggle_comments"

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
space = ":fmt"
ret = ":w!"

[keys.normal.space.x]
p = ":pipe ex_s ip"
o = ":pipe ex_cm oneline"

[keys.normal.space.x.i]
i = ":pipe ex_s i"
p = ":pipe ex_s ip"
f = ":pipe ex_s if"
r = ":pipe ex_s ifr"

