theme = "everforest_dark"

[editor]
shell = ["fish", "-c"]
idle-timeout = 100
color-modes = true
insert-final-newline = true
jump-label-alphabet = "fjdkslaruvmeicwox"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.smart-tab]
supersede-menu = true

[editor.soft-wrap]
enable = true

[keys.normal]
"#" = "toggle_comments"
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
space = ":fmt"
ret = ":w!"

[keys.normal.space.x]
i = ":pipe ex_s ip"
t = ":sh ex_test %{filename}:%{linenumber}"
f = [":pipe-to mix format %{filename}", ":rl"] # Until Lexical formats H sigils
g = ":sh gh_browse %{filename}:%{linenumber}"

[keys.normal.space.x.I]
i = ":pipe ex_s i"
p = ":pipe ex_s ip"
f = ":pipe ex_s if"
r = ":pipe ex_s ifr"

[keys.normal.space.x.c]
s = ":pipe ccase -t snake | tr -d '\n'"
c = ":pipe ccase -t camel | tr -d '\n'"
k = ":pipe ccase -t kebab | tr -d '\n'"
t = ":pipe ccase -t title | tr -d '\n'"

[keys.insert]
S-tab = "move_parent_node_start"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
