[language-server]
lexical = { command = "/Users/pawel/projects/elixir/lexical/_build/dev/package/lexical/bin/start_lexical.sh" }

[[language]]
name = "elixir"
language-servers = [ "lexical" ]

[[language]]
name = "heex"
language-servers = [ "lexical" ]
