[language-server]
lexical = { command = "/Users/pawel/projects/elixir/lexical/_build/dev/package/lexical/bin/start_lexical.sh" }
nextls = { command = "/opt/homebrew/bin/nextls", args = [ "--stdio=true" ] }

[[language]]
name = "elixir"
language-servers = [ "lexical", "nextls" ]

[[language]]
name = "heex"
language-servers = [ "lexical", "nextls" ]
